### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by jhpratt** [rust-linting/design#5]
So far I've been using the following terminology:

- _linter_: the tool that loads and executes lints
- _lint implementation_: the dynamically loadable lint
- _end user_/_lint user_: the person who calls the linter from the command line and expects to receive output from various lints in their terminal (or CI or whatever else as relevant)

This may not be the clearest of terminology. What alternatives are there? I'm not fixed on anything.

**Comment by flip1995** [comment]
From the previous discussions, I propose the following terminology:

- _Driver_: The tool that runs the lints (e.g. a cargo sub-command like `cargo lint`)
- _Linter_: The lint implementation using this API, the thing that is loaded and executed by the _Driver_
- _Lint (implementation)_: The implementation of _a_ lint by a _Linter_.
- _End User_ / _Lint User_: The person who calls the _Driver_ from the command line [...]

**Comment by jplatte** [comment]
I'm strongly in favor of using "linter" for the tool, not for the thing that is loaded and executed by that tool. Still, that thing should probably not be named "lint", since I feel that term has a pretty strong existing meaning, maybe best described as a "code-analysis pass" (e.g. `unused_mut` / `clippy::str_to_string`). I don't really know what to call this dynamically-loadable set of lints (and maybe lint groups, such as `rust-2018-idioms` / `clippy::pedantic`), but here's some ideas:

* linter plugin
* lint package
* lint crate (if lints end up being distributed in source form similar to dev- / build-dependencies)

**Comment by jhpratt** [comment]
- Linter: the thing called by the user (`cargo lint` or similar)
- Driver: the internal code that loads and executes various lints. _Not_ the lints themselves.
- Lint package (or crate as @jplatte mentioned): a set of lints provided as a single library, whatever form that ultimately takes. Likely provides a namespace of some sort.
- Lint implementation: seems to have consensus
- Lint group: common sense definition. I doubt there's any disagreement here.
- End user or lint user: ditto

@jplatte Why not call it a lint? If we're emitting warnings and errors, is that not linting? Code analysis makes it sound like we're doing something completely different.

**Comment by jhpratt** [comment]
Also, this hasn't been explicitly said, but I'll be writing info like this into various markdown documents to put in this (currently nonexistent) repo once consensus is made.

**Comment by jhpratt** [comment]
Documented in the repo.
