### ISSUE TITLE
Question? Do we want to encurrage the usage of this API for statistsics and the like?

### ISSUE THREAD

**Issue by xFrednet** [rust-linting/design#7]
Having a stable rustc API that is used for linting could also be *abused* to create statistics about the code in a nice and future prove manner. For example, Rust and Clippy both use such code to extract lint documentation and I can easily think of other statistics and documentation that could be collected using this API. Do we want to support and even encourage this behavior?

The main blocker for this is probably the [plan to sandbox](https://github.com/rust-linting/design/discussions/1#discussioncomment-1080043) the lint execution (which I'm in favor of). Supporting this could probably as simple as providing an additional interface to write collected data to a file.

**Comment by jhpratt** [comment]
I wouldn't expect this to be included in any form as part of the linter. The stable wrapper over the internal API? I could see it being used that way, but I'm not sure we should specifically tailor to that use case at first.

**Comment by flip1995** [comment]
We shouldn't discourage any usage of the API, but only encourage the correct usage of the API. If people are creative and use the API in another way than intended, I'm ok with this, as long as we're clear what we actively support. So if someone opens an issue "I used this in a way that was never intended and something didn't work", we can just close this issue, since we don't support every use case out there. But I don't see a reason to discourage people from experimenting and limit testing.

**Comment by jhpratt** [comment]
^^ pretty much. Use and abuse as you wish, but it's not our problem if something doesn't work for your exact use case.

**Comment by jhpratt** [comment]
@xFrednet :+1:'d the comments so I presume they are in agreement. Resolving in favor of "do what you want, but we're not going to support other use cases".
